#pragma once


typedef enum asSTREAM_OPTION_E {
    AS_STREAM_OPTION_OFF = 0,
    AS_STREAM_OPTION_NIR,
    AS_STREAM_OPTION_DOT,
    AS_STREAM_OPTION_DEPTH_IMAGE,
    AS_STREAM_OPTION_NIR_DEPTH,
    AS_STREAM_OPTION_BUTT
} AS_STREAM_OPTION_E;

typedef enum CAMERA_TYPE_E {
    AS_CAM_NUWA_XB40 = 0,
    AS_CAM_NUWA_X100,
    AS_CAM_NUWA_HP60,
    AS_CAM_BUTT
} AS_CAMERA_TYPE_E;